name: Build & Deploy
on:
  push:
  workflow_dispatch:


jobs:
  Build: 
    permissions:
      actions: read
      contents: read
      id-token: write  
    uses: CombatWarships/DevOps/.github/workflows/BuildAndDeploy.yml@main
    with:
      CONTAINER_NAME: warshipui
    secrets: 
      DBConnection: none    
      APP_INSIGHTS: ${{secrets.APP_INSIGHTS}}
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}  
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
